import { StyleSheet, Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    backgroundColor: '#0b4f7e',
    flex: 1,
  },
  textoTitulo: {
    color: 'white',
    fontSize: 30,
    marginTop: 35,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  img: {
    width: width * 0.7,
    height: height * 0.3,
    position: 'absolute',
    top: height * 0.6,
    left: width * -0.15,
  },
  boton: {
    width: width * 0.6,
    height: height * 0.113,
    backgroundColor: '#d8c7ce',
    //borderRadius: 12,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    alignSelf: 'flex-start',
    position: 'absolute',
    marginLeft: 12,
    top: 15,
  },
  transBoton1: {
    backgroundColor: '#0b4f7e',
    borderBottomLeftRadius: 40,
    width: width * 0.75,
    height: 50,
    top: -35,
    left: -15,
    position: 'absolute',
  },
  transBoton2: {
    backgroundColor: '#0b4f7e',
    borderTopLeftRadius: 40,
    width: width * 0.75,
    height: 50,
    top: 75,
    left: -15,
    position: 'absolute',
  },
  botonSingUp: {
    width: width * 0.6,
    height: height * 0.113,
    backgroundColor: '#d4ebec',
    //borderRadius: 12,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    alignSelf: 'flex-end',
    position: 'absolute',
    top: 15,
  },
  transBotonSingUp1: {
    backgroundColor: '#0b4f7e',
    borderBottomRightRadius: 40,
    width: '75%',
    height: 50,
    top: -35,
    right: -15,
    position: 'absolute',
    alignSelf: 'flex-end',
  },
  transBotonSingUp2: {
    backgroundColor: '#0b4f7e',
    borderTopRightRadius: 40,
    width: '75%',
    height: 50,
    top: 75,
    right: -15,
    position: 'absolute',
    alignSelf: 'flex-end',
  },
  textoBoton: {
    color: '#0b4f7e',
    fontSize: 18,
    textAlign: 'center',
    marginTop: 15,
    fontWeight: 'bold',
  },
  texto: {
    color: 'white',
    fontSize: 20,
    textAlign: 'center',
    marginTop: height * 0.2,
  },
  logo: {
    width: width * 0.7,
    height: height * 0.3,
    alignSelf: 'center',
  },
});
