import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    backgroundColor: '#0b4f7e',
    flex: 1,
  },
  textoTitulo: {
    color: 'white',
    fontSize: 30,
    marginTop: 35,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  img: {
    width: 300,
    height: 200,
    position: 'absolute',
    top: 300,
    left: -70,
  },
  boton: {
    width: 200,
    height: 60,
    backgroundColor: '#d8c7ce',
    //borderRadius: 12,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    alignSelf: 'flex-start',
    position: 'absolute',
    marginLeft: 12,
    top: 15,
  },
  transBoton1: {
    backgroundColor: '#0b4f7e',
    borderBottomLeftRadius: 40,
    width: '75%',
    height: 50,
    top: -35,
    left: -15,
    position: 'absolute',
  },
  transBoton2: {
    backgroundColor: '#0b4f7e',
    borderTopLeftRadius: 40,
    width: '75%',
    height: 50,
    top: 75,
    left: -15,
    position: 'absolute',
  },
  botonSingUp: {
    width: 200,
    height: 60,
    backgroundColor: '#d4ebec',
    //borderRadius: 12,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    alignSelf: 'flex-end',
    position: 'absolute',
    top: 15,
  },
  transBotonSingUp1: {
    backgroundColor: '#0b4f7e',
    borderBottomRightRadius: 40,
    width: '75%',
    height: 50,
    top: -35,
    right: -15,
    position: 'absolute',
    alignSelf: 'flex-end',
  },
  transBotonSingUp2: {
    backgroundColor: '#0b4f7e',
    borderTopRightRadius: 40,
    width: '75%',
    height: 50,
    top: 75,
    right: -15,
    position: 'absolute',
    alignSelf: 'flex-end',
  },
  textoBoton: {
    color: '#0b4f7e',
    fontSize: 18,
    textAlign: 'center',
    marginTop: 15,
    fontWeight: 'bold',
  },
  texto: {
    color: 'white',
    fontSize: 20,
    textAlign: 'center',
    marginTop: 150,
  },
  logo: {
    width: 350,
    height: 150,
    alignSelf: 'center',
  },
});
